add wave -position end  sim:/t_radix/CLK
add wave -position end  sim:/t_radix/input_ready
add wave -position end  sim:/t_radix/result_ready
add wave -position end  sim:/t_radix/valid

add wave -position end  sim:/t_radix/comp/valid_list
add wave -position end  sim:/t_radix/comp/ready_list

add wave -position end  sim:/t_radix/X0
add wave -position end  sim:/t_radix/X1
add wave -position end  sim:/t_radix/X2
add wave -position end  sim:/t_radix/X3
add wave -position end  sim:/t_radix/X4
add wave -position end  sim:/t_radix/X5
add wave -position end  sim:/t_radix/X6
add wave -position end  sim:/t_radix/X7
add wave -position end  sim:/t_radix/X8
add wave -position end  sim:/t_radix/X9
add wave -position end  sim:/t_radix/X10
add wave -position end  sim:/t_radix/X11
add wave -position end  sim:/t_radix/X12
add wave -position end  sim:/t_radix/X13
add wave -position end  sim:/t_radix/X14
add wave -position end  sim:/t_radix/X15
add wave -position end  sim:/t_radix/Z0_RE
add wave -position end  sim:/t_radix/Z0_IM
add wave -position end  sim:/t_radix/Z1_RE
add wave -position end  sim:/t_radix/Z1_IM
add wave -position end  sim:/t_radix/Z2_RE
add wave -position end  sim:/t_radix/Z2_IM
add wave -position end  sim:/t_radix/Z3_RE
add wave -position end  sim:/t_radix/Z3_IM
add wave -position end  sim:/t_radix/Z4_RE
add wave -position end  sim:/t_radix/Z4_IM
add wave -position end  sim:/t_radix/Z5_RE
add wave -position end  sim:/t_radix/Z5_IM
add wave -position end  sim:/t_radix/Z6_RE
add wave -position end  sim:/t_radix/Z6_IM
add wave -position end  sim:/t_radix/Z7_RE
add wave -position end  sim:/t_radix/Z7_IM
add wave -position end  sim:/t_radix/Z8_RE
add wave -position end  sim:/t_radix/Z8_IM
add wave -position end  sim:/t_radix/Z9_RE
add wave -position end  sim:/t_radix/Z9_IM
add wave -position end  sim:/t_radix/Z10_RE
add wave -position end  sim:/t_radix/Z10_IM
add wave -position end  sim:/t_radix/Z11_RE
add wave -position end  sim:/t_radix/Z11_IM
add wave -position end  sim:/t_radix/Z12_RE
add wave -position end  sim:/t_radix/Z12_IM
add wave -position end  sim:/t_radix/Z13_RE
add wave -position end  sim:/t_radix/Z13_IM
add wave -position end  sim:/t_radix/Z14_RE
add wave -position end  sim:/t_radix/Z14_IM
add wave -position end  sim:/t_radix/Z15_RE
add wave -position end  sim:/t_radix/Z15_IM

add wave -position end  sim:/t_radix/comp/STATE
add wave -position end  sim:/t_radix/comp/counter
